version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - redis
      - db
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env

  celery_worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6379"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
      build: ./frontend
      container_name: frontend
      depends_on:
        - backend
      ports:
        - "3000:80"
volumes:
  pgdata:
